# Generated by Django 5.1 on 2024-09-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated',
        ),
    ]
