# Generated by Django 5.1 on 2024-09-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_city_time_create_remove_city_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='country_code',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
