# Generated by Django 5.1 on 2024-09-16 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_country_code_weather_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_run_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
